/**
 * Environment Setup Script
 * Reads from .env file and generates Angular environment files
 * 
 * Usage: node scripts/set-env.js
 */

const fs = require('fs');
const path = require('path');

// Load .env file if it exists
const envPath = path.join(__dirname, '..', '.env');
const env = { ...process.env };

if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  envContent.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      env[key.trim()] = valueParts.join('=').trim();
    }
  });
} else {
  console.log('No .env file found, using system environment variables.');
}

const projectId = env.SANITY_PROJECT_ID || '';
const dataset = env.SANITY_DATASET || 'production';
const apiVersion = env.SANITY_API_VERSION || '2023-05-03';

if (!projectId) {
  console.error('Error: SANITY_PROJECT_ID is required in .env');
  process.exit(1);
}

const devEnv = `// Auto-generated by scripts/set-env.js - DO NOT EDIT DIRECTLY
// Run 'node scripts/set-env.js' to regenerate from .env

export const environment = {
  production: false,
  sanity: {
    projectId: '${projectId}',
    dataset: '${dataset}',
    apiVersion: '${apiVersion}',
    useCdn: true
  }
};
`;

const prodEnv = `// Auto-generated by scripts/set-env.js - DO NOT EDIT DIRECTLY
// Run 'node scripts/set-env.js' to regenerate from .env

export const environment = {
  production: true,
  sanity: {
    projectId: '${projectId}',
    dataset: '${dataset}',
    apiVersion: '${apiVersion}',
    useCdn: true
  }
};
`;

const envDir = path.join(__dirname, '..', 'src', 'environments');
fs.writeFileSync(path.join(envDir, 'environment.ts'), devEnv);
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), prodEnv);

console.log('✓ Generated environment.ts');
console.log('✓ Generated environment.prod.ts');
console.log(`  Project ID: ${projectId}`);
console.log(`  Dataset: ${dataset}`);
